import Head from 'next/head';
import type { AppProps } from 'next/app';
import { ToastContainer } from 'react-toastify';
import AppWrapper from '@/common/components/AppWrapper';
import AppProvider from '@/common/context';
import { basePath } from '@/common/constants';
import 'animate.css';
import 'react-toastify/dist/ReactToastify.css';
import '@/common/styles/globals.css';
function MyApp({ Component, pageProps, router }: AppProps) {
  const pagePath = router.asPath.split('?')[0];

  return (
    <>
      <Head>
        <title>Template Webview</title>
        <meta
          name="viewport"
          content="minimum-scale=1, initial-scale=1, width=device-width, shrink-to-fit=no, viewport-fit=cover"
        />
        <meta name="description" content="Generated by Lila Software Studio" />
        <link rel="icon" href={`${basePath}/favicon.ico`} />
      </Head>
      <AppProvider>
        <ToastContainer
          position="top-right"
          autoClose={6000}
          hideProgressBar={false}
          newestOnTop
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="colored"
        />

        <AppWrapper key={pagePath}>
          <Component {...pageProps} />
        </AppWrapper>
      </AppProvider>
    </>
  );
}

export default MyApp;
